# Generated by Django 5.1.1 on 2024-09-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("plant_id", models.AutoField(primary_key=True, serialize=False)),
                ("plant_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_path",
                    models.ImageField(upload_to="pollenvision/imagesimport/%Y/%m/%d"),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pollenvision.plant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pollenvision.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("viability", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grain_count", models.IntegerField()),
                ("error", models.DecimalField(decimal_places=2, max_digits=5)),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pollenvision.image",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pollenvision.plant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pollenvision.profile"
            ),
        ),
    ]
